@Reborn_Fashion_Api_HostAddress = http://localhost:5157

POST {{Reborn_Fashion_Api_HostAddress}}/listings/
Accept: application/json
Content-Type: application/json

{
  "title": "Test Listing",
  "description": "A listing to be used for testing",
  "start": "2024-04-15T17:45:20.000Z",
  "end": "2024-04-15T17:45:30.000Z"
}
###
